import{a as L,S as v,i as a}from"./assets/vendor-LvtvrCkc.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const f of r.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&n(f)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const w="53393653-1acdc9704f6308d207f4a2045",B="https://pixabay.com/api/";async function P(e,t=1){const s={key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await L.get(B,{params:s})).data}const p=document.querySelector(".gallery"),l=document.getElementById("loader-overlay"),u=document.getElementById("load-button");function S(e){return`
        <li class="gallery-item">
            <a href="${e.largeImageURL}" class="gallery-link"> 
                <img src="${e.webformatURL}" 
                     alt="${e.tags}" 
                     class="gallery-image">
            </a>
        <div class="info">
            <p class="info-item"><b>Likes</b>${e.likes}</p>
            <p class="info-item"><b>Views</b>${e.views}</p>
            <p class="info-item"><b>Comments</b>${e.comments}</p>
            <p class="info-item"><b>Downloads</b>${e.downloads}</p>
        </div>
    </li>
    `}const q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function E(e){const t=e.map(S).join("");p.insertAdjacentHTML("beforeend",t),q.refresh()}function I(){p.innerHTML=""}function h(){l&&l.classList.remove("hidden")}function m(){l&&l.classList.add("hidden")}function $(){u&&u.classList.remove("hidden")}function i(){u&&u.classList.add("hidden")}let d=1,g="",y=0;const M=15,c=document.querySelector(".form"),O=c.elements.query,R=document.getElementById("load-button"),H=document.querySelector(".gallery");m();i();c.addEventListener("submit",async e=>{e.preventDefault();const t=O.value.trim();if(!t){a.warning({message:"Please enter a search term!",position:"topRight"});return}d=1,g=t,i(),I(),h();const s=await b(!0);if(s&&s.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),m(),c.reset();return}c.reset()});R.addEventListener("click",async()=>{d+=1,i(),h();const e=await b(!1);e&&e.hits.length>0&&x()});async function b(e){try{const t=await P(g,d),s=t.hits,n=t.totalHits;return y=Math.ceil(n/M),s.length?(E(s),d<y?$():(i(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})),t):(i(),e||a.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}),t)}catch(t){a.error({message:"Error",position:"topRight"}),console.error(t)}finally{m()}}function x(){const e=H.querySelector(".gallery-item");if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
